{ config, lib, pkgs, ... }:

# The Android toolchain behind find-best-job's Android app: a TWA (the site in
# Chrome, full screen) generated by Bubblewrap, built with Gradle and tested
# on headless emulators by scripts/android-e2e.mjs in that repo.
#
# Homebrew (configuration.nix) provides the JDK and the command-line tools.
# Everything else is Google's SDK in ~/Library/Android/sdk, which is not in
# Homebrew or nixpkgs in a form that runs the arm64 emulator, so the
# activation step below installs whatever of it is missing.
let
  sdk = "${config.home.homeDirectory}/Library/Android/sdk";
  jdk = "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk";

  # Only what the app builds against and the two emulators it is tested on:
  # compileSdk 36 needs platform 36 and Bubblewrap pins build-tools 36.1.0;
  # the Android 15 image is the current phone, the Android 11 image a phone
  # with an old Chrome (91), the oldest one that runs the dashboard.
  packages = [
    "platform-tools"
    "emulator"
    "cmdline-tools;latest"
    "platforms;android-36"
    "build-tools;36.1.0"
    "system-images;android-35;google_apis_playstore;arm64-v8a"
    "system-images;android-30;google_apis_playstore;arm64-v8a"
  ];

  avds = [
    {
      name = "fbj-pixel";
      image = "system-images;android-35;google_apis_playstore;arm64-v8a";
      device = "pixel_7";
    }
    {
      name = "fbj-antigo";
      image = "system-images;android-30;google_apis_playstore;arm64-v8a";
      device = "pixel_3a";
    }
  ];
in
{
  home.sessionVariables = {
    JAVA_HOME = lib.mkForce "${jdk}/Contents/Home";
    ANDROID_HOME = sdk;
  };

  home.sessionPath = [
    "${sdk}/platform-tools"
    "${sdk}/emulator"
  ];

  programs.mise.globalConfig.tools."npm:@bubblewrap/cli" = "latest";

  home.activation.androidSdk = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    sdkmanager=/opt/homebrew/share/android-commandlinetools/cmdline-tools/latest/bin/sdkmanager
    if [ -n "''${DRY_RUN_CMD:-}" ]; then
      echo "Would install missing Android SDK packages into ${sdk}"
    elif [ ! -x "$sdkmanager" ] || [ ! -d "${jdk}" ]; then
      echo "Android SDK skipped: the android-commandlinetools cask or openjdk@17 is not installed yet; rebuild again once Homebrew has run."
    else
      export JAVA_HOME="${jdk}/Contents/Home"
      missing=()
      for pkg in ${lib.escapeShellArgs packages}; do
        [ -e "${sdk}/''${pkg//;//}" ] || missing+=("$pkg")
      done
      if [ "''${#missing[@]}" -gt 0 ]; then
        mkdir -p "${sdk}"
        yes | "$sdkmanager" --sdk_root="${sdk}" --licenses >/dev/null 2>&1 || true
        "$sdkmanager" --sdk_root="${sdk}" "''${missing[@]}" >/dev/null
      fi

      # Bubblewrap refuses an SDK path with neither a `tools` nor a `bin`
      # folder, a check from the pre-2020 SDK layout.
      ln -sfn "${sdk}/cmdline-tools/latest" "${sdk}/tools"

      avdmanager="${sdk}/cmdline-tools/latest/bin/avdmanager"
      export PATH="${pkgs.gawk}/bin:$PATH"
      ${lib.concatMapStrings (avd: ''
        if [ ! -d "$HOME/.android/avd/${avd.name}.avd" ]; then
          echo no | "$avdmanager" create avd -n ${avd.name} -k "${avd.image}" -d ${avd.device} >/dev/null
        fi
      '') avds}

      # Bubblewrap asks for these two paths interactively on first run, and
      # rewrites the file itself on `bubblewrap updateConfig`, so it is written
      # once here rather than linked read-only from the store.
      if [ ! -e "$HOME/.bubblewrap/config.json" ]; then
        mkdir -p "$HOME/.bubblewrap"
        printf '{"jdkPath":"%s","androidSdkPath":"%s"}\n' "${jdk}" "${sdk}" > "$HOME/.bubblewrap/config.json"
      fi
    fi
  '';
}
